export type PokeType = (typeof POKE_TYPES)[number]
export type PokeTypeJp = (typeof POKE_TYPE_JP)[PokeType]
export type PokeTypeKanji = (typeof POKE_TYPE_KANJI)[PokeType]

export const POKE_TYPES = [
  'normal',
  'fire',
  'water',
  'grass',
  'electric',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'phychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
] as const

export const POKE_TYPE_JP = {
  normal: 'ノーマル',
  fire: 'ほのお',
  water: 'みず',
  grass: 'くさ',
  electric: 'でんき',
  ice: 'こおり',
  fighting: 'かくとう',
  poison: 'どく',
  ground: 'じめん',
  flying: 'ひこう',
  phychic: 'エスパー',
  bug: 'むし',
  rock: 'いわ',
  ghost: 'ゴースト',
  dragon: 'ドラゴン',
  dark: 'あく',
  steel: 'はがね',
} as const satisfies Record<PokeType, string>
export const POKE_TYPE_KANJI = {
  normal: '普',
  fire: '炎',
  water: '水',
  grass: '草',
  electric: '電',
  ice: '氷',
  fighting: '闘',
  poison: '毒',
  ground: '地',
  flying: '飛',
  phychic: '超',
  bug: '虫',
  rock: '岩',
  ghost: '霊',
  dragon: '龍',
  dark: '悪',
  steel: '鋼',
} as const satisfies Record<PokeType, string>
